# See https://pre-commit.com/ for usage and config
default_language_version:
    python: python3.9


repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: ['--autofix']
  - id: trailing-whitespace

- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: pipenv run isort --profile black
    types: [python]

  - id: isort-full
    name: isort
    stages: [post-commit]
    always_run: true
    language: system
    entry: pipenv run isort --profile black --diff .
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pipenv run black
    types: [python]

  - id: black-full
    name: black
    stages: [post-commit]
    always_run: true
    language: system
    entry: pipenv run black --check .
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pipenv run flake8
    types: [python]
    exclude: setup.py

  - id: flake8-full
    name: flake8
    stages: [post-commit]
    always_run: true
    language: system
    entry: pipenv run flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: pipenv run mypy
    types: [python]
    require_serial: true

  - id: mypy-full
    name: mypy
    stages: [post-commit]
    always_run: true
    language: system
    entry: pipenv run mypy
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pipenv run pytest
    types: [python]
    pass_filenames: false

  - id: pytest-full
    name: pytest with 100% coverage
    stages: [post-commit]
    always_run: true
    language: system
    entry: pipenv run pytest --cov --cov-fail-under=100
    types: [python]
    pass_filenames: false
